### ISSUE TITLE
CSS 'white-space: pre-wrap' for code blocks?

### ISSUE THREAD

**Issue by ernstki** [ernstki/pinboard-usermods#9]
Looks OK, still copies fine. The horizontal scrollbar appearance (on Linux, anyway) is just not good.

```css
div.description pre,
div.description code
{
  white-space: pre-wrap;
  /*overflow-x: scroll;*/
  line-height: 1em;
}
```
